algoritmo "proje8to_calculadora"
var
   a, b: real
inicio
      escreval ("=======CALCULADORA=======")
      escreva ("DIGITE O PRIMEIRO NÚMERO: ")
      leia (a)
      escreva ("DIGITE O SEGUNDO NÚMERO: ")
      leia (b)
      escreval ("========RESULTADO========")
      escreval()
      escreval (a, " +", b, " =", a+b)
      escreval (a, " -", b, " =", a-b)
      escreval (a, " x", b, " =", a*b)
      escreval (a, " /", b, " =", a/b)
fimalgoritmo
